#!/usr/bin/env python3
"""Compile all guest posting sites from research into a single deduplicated JSON."""
import json
from urllib.parse import urlparse

# All sites collected from 3 research agents
all_sites = [
    # === BATCH 1: Home Improvement & Renovation ===
    {"name": "Urban Splatter", "url": "https://www.urbansplatter.com/write-for-us-home-improvement/", "email": "contact@urbansplatter.com", "category": "Home Improvement", "notes": "DA 47, DR 61. ~300 words, up to 3 dofollow links."},
    {"name": "The Global Hues", "url": "https://theglobalhues.com/write-for-us-home-improvement-home-renovation-home-decor-remodeling-guest-posts/", "email": "info@theglobalhues.com", "category": "Home Improvement", "notes": "900-1500 words, Google Docs/Word. Nominal fee."},
    {"name": "Archinomy", "url": "https://www.archinomy.com/submit-a-guest-post/", "email": "N/A", "category": "Architecture", "notes": "Min 1000 words. Only 1 outbound link. 14 day response."},
    {"name": "Interior Designer Trends", "url": "https://interiordesignertrends.com/write-for-us/", "email": "interiordesignertrends@gmail.com", "category": "Interior Design", "notes": "700+ words, min 2 images. Decor, carpets, lighting, flooring."},
    {"name": "Kooihaus", "url": "https://kooihaus.com/write-for-us-submit-guest-post/", "email": "info@kooihaus.com", "category": "Home Decor", "notes": "Min 700 words. Published within 24h after approval."},
    {"name": "Shine Your Light Blog", "url": "https://shineyourlightblog.com/guest-post/", "email": "info@shineyourlightblog.com", "category": "DIY", "notes": "800-3000 words. DIY, crafts, home decor, home improvement."},
    {"name": "Remodelaholic", "url": "https://www.remodelaholic.com/be-featured/", "email": "N/A", "category": "Home Improvement", "notes": "Accepts home improvement how-to projects, organizing, decorating."},
    {"name": "Home Automation Talks", "url": "https://homeautomationtalks.com/write-for-us-home-automation/", "email": "content@homeautomationtalks.com", "category": "Smart Home", "notes": "Min 1000 words. 1-2 backlinks. Smart devices, IoT, lighting."},
    {"name": "Smart Devices Help", "url": "https://www.smartdeviceshelp.com/write-for-us", "email": "editor@smartdeviceshelp.com", "category": "Smart Home", "notes": "1000-1500 words. Paid: $100. Links become no-follow after 12 months."},
    {"name": "Smart Home Geeks", "url": "https://www.smarthomegeeks.co.uk/write-for-us/", "email": "N/A", "category": "Smart Home", "notes": "UK-focused. Pitch first with bullets. No sales material."},
    {"name": "The Web Science", "url": "https://www.thewebscience.com/smart-home-write-for-us/", "email": "contact@thewebscience.com", "category": "Smart Home", "notes": "Min 500 words. Home automation, smart locks, cameras, IoT."},
    {"name": "Smart Home Perfected", "url": "https://www.smarthomeperfected.com/write-for-us/", "email": "sales@smarthomeperfected.com", "category": "Smart Home", "notes": "Phone: +1 (385) 312-0189. Diverse smart home perspectives."},
    {"name": "SmartHomeBit", "url": "https://www.smarthomebit.com/write-for-us/", "email": "N/A", "category": "Smart Home", "notes": "Guest blog writers for smart home technology."},
    {"name": "Landlord Tips", "url": "https://landlordtips.com/write-for-us", "email": "info@landlordtips.com", "category": "Real Estate", "notes": "Min 1000 words. American English. Max 2 links. Google Docs preferred."},
    {"name": "Reinvestor", "url": "https://www.reinvestor.com/write-us/", "email": "N/A", "category": "Real Estate", "notes": "RE investing, law, accounting, finance, tax, landlording."},
    {"name": "CREST Real Estate Network", "url": "https://crestnetwork.com/write-for-us/", "email": "editor@crestnetwork.com", "category": "Real Estate", "notes": "Articles 1200-2500 words, guest posts 600-1200. Max 2 links. 5 day response."},
    {"name": "Estate & Manor Magazine", "url": "https://www.estateandmanor.com/write-for-us/", "email": "contact@estateandmanor.com", "category": "Real Estate", "notes": "Must be industry professional. No sales material. Author backlinks."},
    {"name": "Developer Gang", "url": "https://developergang.com/write-for-us-real-estate-blogs", "email": "developergang1@gmail.com", "category": "Real Estate", "notes": "Min 420 words. Include full name, bio, website/social links."},
    {"name": "Market Watch Media", "url": "https://www.marketwatchmedia.com/property-manager-write-for-us-and-submit-post/", "email": "contact@marketwatchmedia.com", "category": "Real Estate", "notes": "Min 500 words. No promotional content. Property management focus."},
    {"name": "Long Beach Property Management", "url": "https://longbeachpropertymanagement.com/contribute-write-for-us/", "email": "brians@longbeachpropertymanagement.com", "category": "Real Estate", "notes": "500-700 words. Max 2 no-follow links. Include image."},
    {"name": "DALTX Real Estate", "url": "https://daltxrealestate.com/guest-post/", "email": "info@daltxrealestate.com", "category": "Real Estate", "notes": "500-1200 words. No AI. Max 3 links. Dofollow. DFW focus."},
    {"name": "Real Estate Marketing Blog", "url": "https://www.realestatemarketingblog.org/contact-us/guest-post-guidelines/", "email": "N/A", "category": "Real Estate", "notes": "Min 1500 words. 145K Twitter followers, 45K email subs."},
    {"name": "The Roof Pros", "url": "https://www.theroofpros.co.uk/write-for-us/", "email": "theroofpros3@gmail.com", "category": "Roofing", "notes": "1000-1200 words. 1 dofollow backlink. Google Doc/Word."},
    {"name": "HP Roofing", "url": "https://hproofing.ie/write-for-us", "email": "info@hproofing.ie", "category": "Roofing", "notes": "Min 1000 words. 1 relevant hyperlink. High-res images."},
    {"name": "Arizona's Finest Roofing", "url": "https://arizonasfinestroofing.com/write-for-us", "email": "office2@arizonasfinestroofing.com", "category": "Roofing", "notes": "Min 700 words. 1 link. Arizona/US focus."},
    {"name": "Geo Roofers", "url": "https://georoofers.com/write-for-us/", "email": "N/A", "category": "Roofing", "notes": "1200-2500 words. Unique content only."},
    {"name": "Roofing Experts Hub", "url": "https://roofingexpertshub.com/write-for-us/", "email": "N/A", "category": "Roofing", "notes": "Roof maintenance, repair, materials, energy-efficient solutions."},
    {"name": "CR Lansing Roofing", "url": "https://crlansingroofing.com/write-for-us/", "email": "N/A", "category": "Roofing", "notes": "Roofing and home improvement topics."},
    {"name": "Kitchen and Bath Resources", "url": "https://kitchenandbathresources.com/write-for-us/", "email": "info@kitchenandbathresources.com", "category": "Kitchen & Bathroom", "notes": "800-1500 words. Max 2 backlinks. No affiliate links."},
    {"name": "3D Decorative", "url": "https://3ddecorative.com/write-for-us/", "email": "N/A", "category": "Kitchen & Bathroom", "notes": "800-1500 words. Paid: $30/post or $99/5. High-res images."},
    {"name": "MyKukun", "url": "https://mykukun.com/write-for-us", "email": "N/A", "category": "Home Renovation", "notes": "800-3000 words. US-focused. Max 1 link (no-follow)."},
    {"name": "Home Kitchen Buzz", "url": "https://www.homekitchenbuzz.com/write-for-us/", "email": "N/A", "category": "Kitchen & Bathroom", "notes": "Home, kitchen, bathroom topics including DIY."},
    {"name": "Wikilawn", "url": "https://www.wikilawn.com/contact/write-for-us/", "email": "submit@wikilawn.com", "category": "Landscaping", "notes": "600-2500 words. Google Docs preferred. No sales pitches."},
    {"name": "Loaded Landscapes", "url": "https://loadedlandscapes.com/write-for-us/", "email": "N/A", "category": "Landscaping", "notes": "Landscaping-focused blog."},
    {"name": "ECOgardener", "url": "https://ecogardener.com/pages/write-for-us", "email": "info@ecogardener.com", "category": "Gardening", "notes": "Houston, TX. Landscape fabric, gardening tools, soil."},
    {"name": "Fantastic Gardeners Blog", "url": "https://blog.fantasticgardeners.co.uk/write-for-us/", "email": "community@fantasticservices.com", "category": "Gardening", "notes": "Gardening, landscaping, turfing, fencing, tree surgery."},
    {"name": "Home & Design Magazine", "url": "https://www.homeanddesign.com/write-for-us-home-design/", "email": "editorial@homeanddesign.com", "category": "Interior Design", "notes": "800-1500 words. Outdoor/garden, landscaping, interior. 5-7 day response."},
    {"name": "Vegega", "url": "https://www.vegega.com/pages/write-for-us", "email": "N/A", "category": "Gardening", "notes": "800-1000 words. Experienced gardeners. Planting and garden ideas."},
    {"name": "TN Nursery", "url": "https://www.tnnursery.net/pages/write-for-us", "email": "Sales@tennesseewholesalenursery.com", "category": "Gardening", "notes": "Paid opportunities. Eco-gardening and native landscaping."},
    {"name": "City Furnish", "url": "https://cityfurnish.com/blog/write-for-us", "email": "alpana@cityfurnish.com", "category": "Furniture", "notes": "DA 61. Furniture rental, interior design, sustainability. Pitch first."},
    {"name": "Bob Mills Furniture", "url": "https://www.bobmillsfurniture.com/write-for-us", "email": "N/A", "category": "Furniture", "notes": "Min 1000 words. Furniture, home design, outdoor, remodels."},
    {"name": "Giving Tree Home", "url": "https://www.givingtreehome.com/pages/write-for-us", "email": "sales@givingtreehome.com", "category": "Furniture", "notes": "Furniture selection and design concepts."},
    {"name": "Sleekform Furniture", "url": "https://sleekform.com/pages/write-for-us", "email": "N/A", "category": "Furniture", "notes": "Ergonomic and modern furniture blog."},
    {"name": "Security Forward", "url": "https://www.securityforward.com/write-for-us/", "email": "N/A", "category": "Home Security", "notes": "1000-1500 words. Home, corporate, personal security."},
    {"name": "Heimdal Security", "url": "https://heimdalsecurity.com/blog/write-for-us/", "email": "guestauthors@heimdalsecurity.com", "category": "Home Security", "notes": "Email 1-2 topic ideas. Security technology."},
    {"name": "Homey Improvements", "url": "https://homeyimprovements.com/write-for-us/", "email": "info@homeyimprovements.com", "category": "Home Improvement", "notes": "Min 1000 words. 5+ images. USA, UK, AU, CA. DA 38."},
    {"name": "Home Improve Idea", "url": "https://homeimproveidea.com/write-for-us/", "email": "homeimproveidea@gmail.com", "category": "Home Improvement", "notes": "Min 800 words. No AI. Max 1-2 dofollow links. DA 55."},
    {"name": "Renovation Insights", "url": "https://renovationinsights.home.blog/write-for-us/", "email": "ayan@techdigitalgroups.com", "category": "Home Renovation", "notes": "Home improvement and real estate topics."},
    {"name": "Estimate Florida Consulting", "url": "https://estimatorflorida.com/write-for-us-home-renovation-guest-post/", "email": "N/A", "category": "Home Renovation", "notes": "Min 1200 words. SEO-optimized. Published 3-4 business days."},
    {"name": "Naik Interiors", "url": "https://naikinteriors.com/write-for-us-furniture-home-decor-architecture-realestate/", "email": "hello@naikinteriors.com", "category": "Interior Design", "notes": "800+ words. No AI. 1 dofollow link. Published 2-3 days."},
    {"name": "House Ploy", "url": "https://houseploy.com/write-for-us/", "email": "teamhouseploy@gmail.com", "category": "Home Decor", "notes": "800-1500 words. 1 dofollow + 2 nofollow. Conversational tone."},
    {"name": "KEA Home", "url": "https://kea-home.com/write-for-us-home/", "email": "info.kea.home@gmail.com", "category": "Home Improvement", "notes": "No strict word limit. No AI. ~3 day review."},
    {"name": "RenoHood", "url": "https://www.renohood.com/write-for-us/", "email": "N/A", "category": "Home Renovation", "notes": "Min 1500 words. Appliances, flooring, roofing, landscaping."},
    {"name": "Erisa Projects", "url": "https://erisaprojects.com/write-for-us/", "email": "N/A", "category": "Construction", "notes": "1200-2500 words. Max 5 backlinks. Submit 3 title ideas first. Free."},
    {"name": "Northerncult", "url": "https://northerncult.com/how-to-start-guest-blogging-with-northerncult/", "email": "elena@northerncult.com", "category": "Interior Design", "notes": "Min 1000 words. Include images/GIFs. 5-7 days review."},
    {"name": "Smithers of Stamford", "url": "https://www.smithersofstamford.com/content/guest-posting", "email": "gp@smithersofstamford.com", "category": "Furniture", "notes": "400-1500 words. No AI. Social media promotion included."},
    {"name": "Dalton Flooring Design", "url": "https://www.daltonflooringdesign.com/write-for-us-sponsored-posts/", "email": "netherlandsmark@proton.me", "category": "Flooring", "notes": "1000-3000 words. Copyscape checked. Up to 3 links. 2-4 days."},
    {"name": "Concrete Floor Pros", "url": "https://concretefloorpros.com/write-for-us/", "email": "N/A", "category": "Flooring", "notes": "Min 1000 words. No cost for accepted articles."},
    {"name": "Flooring Hunt", "url": "https://flooringhunt.com/write-for-us/", "email": "N/A", "category": "Flooring", "notes": "Dedicated flooring resource."},
    {"name": "Shakti Home Style", "url": "https://www.shaktihomestyle.com/write-for-us/", "email": "N/A", "category": "Flooring", "notes": "Min 500 words. Home and flooring topics."},

    # === BATCH 2: More Home Improvement Sites ===
    {"name": "Home Guest Post", "url": "https://homeguestpost.com/write-for-us-home/", "email": "sales@seovalleypro.com", "category": "Home Improvement", "notes": "DIY, organization, home decor. Author credit + backlinks."},
    {"name": "Propaura", "url": "https://propaura.com/write-for-us/", "email": "info@propaura.com", "category": "Real Estate", "notes": "Min 600 words. Real estate, home decor, home improvement, finance."},
    {"name": "House Whirl", "url": "https://housewhirl.com/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Min 1000 words. Innovative home tips."},
    {"name": "Trionds", "url": "https://www.trionds.com/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "High DA. Home decor, renovation, interior design."},
    {"name": "About Wall Art", "url": "https://aboutwallart.com/pages/write-for-us", "email": "N/A", "category": "Home Decor", "notes": "UK-based. Interior designers, stylists welcome."},
    {"name": "All Around Moving", "url": "https://www.allaroundmoving.com/write-for-us/", "email": "N/A", "category": "Moving & Relocation", "notes": "Moving, relocation, real estate, business tips, home decor."},
    {"name": "Maid Sailors", "url": "https://maidsailors.com/write-for-us-guest-posts/", "email": "N/A", "category": "Home Cleaning", "notes": "Home cleaning and organization guest posts."},
    {"name": "Home Improvement Help Center", "url": "https://www.homeimprovementhelpcenter.com/submit-home-improvement-guest-blog-post/", "email": "homeimprovementhelpcenter@gmail.com", "category": "Home Improvement", "notes": "550+ words. Subject: Write for US."},
    {"name": "Beautiful House Tips", "url": "https://beautifulhousetips.com/write-for-us/", "email": "contact@beautifulhousetips.com", "category": "Home Improvement", "notes": "Min 800 words. Home design, DIY renovations, sustainable living."},
    {"name": "Green Eco Dream", "url": "https://greenecodream.com/home-improvement-write-for-us/", "email": "hi@greenecodream.com", "category": "Sustainable Home", "notes": "Eco home improvements."},
    {"name": "Get Green Now", "url": "https://get-green-now.com/write-for-us/", "email": "N/A", "category": "Sustainable Home", "notes": "Ecology, environment, sustainable living."},
    {"name": "Tiny Life House", "url": "https://tinylifehouse.com/write-for-us/", "email": "N/A", "category": "Tiny House", "notes": "700-1400 words. Tiny house design, DIY, off-grid, financing."},
    {"name": "Tiny Society", "url": "https://www.tinysociety.co/write-for-us/", "email": "N/A", "category": "Tiny House", "notes": "Active tiny living community. Author credit with bio link."},
    {"name": "Tiny Home Tours", "url": "https://www.tinyhometours.com/write-for-us", "email": "N/A", "category": "Tiny House", "notes": "Traditional tiny houses, container homes, skoolies, vans."},
    {"name": "WillyHomes", "url": "https://willyhomes.com/home-improvement-write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Reputed niche blog."},
    {"name": "Snoozye", "url": "https://snoozye.com/home-improvement-write-for-us/", "email": "N/A", "category": "Home Decor", "notes": "Expanding into home decor. New and experienced contributors."},
    {"name": "FangWallet", "url": "https://fangwallet.com/write-for-us-a-insurance-blog-post/", "email": "N/A", "category": "Home Insurance", "notes": "Min 1500 words. Insurance including home insurance."},
    {"name": "Brilliant Insurance", "url": "https://brilliantinsurance.us/write-for-us", "email": "N/A", "category": "Home Insurance", "notes": "1000-1500 words. All insurance types including homeowners."},
    {"name": "Richey Insurance Agency", "url": "https://richeyinsurance.com/write-for-us/", "email": "editor@richeyinsurance.com", "category": "Home Insurance", "notes": "800+ words. Homeowners insurance tips."},
    {"name": "Super Packers Movers", "url": "https://superpackersmovers.com/write-for-us/", "email": "N/A", "category": "Moving & Relocation", "notes": "Min 800 words. Moving, logistics, relocation."},
    {"name": "Label Bazaars", "url": "https://www.labelbazaars.com/movers-write-for-us/", "email": "contact@labelbazaars.com", "category": "Moving & Relocation", "notes": "Min 500 words. Movers and moving industry."},
    {"name": "Green Garden Landscaping", "url": "https://www.greengardenlandscape.com/write-for-us-guest-post-outdoor-lawn-landscaping-improvement", "email": "N/A", "category": "Landscaping", "notes": "Google Docs. Include 3 internal links to their site."},
    {"name": "Tree Removal Costs Calculator", "url": "https://treeremovalcostscalculator.com/write-for-us-tree-gardening-landscaping-home-improvement/", "email": "N/A", "category": "Landscaping", "notes": "Tree care, gardening, landscaping. Dofollow backlink."},
    {"name": "Bunny Garden", "url": "https://www.bunnygarden.ca/write-for-us/", "email": "N/A", "category": "Gardening", "notes": "800-1000 words. Planting and maintenance tips. Canadian."},
    {"name": "Big Blog of Gardening", "url": "https://www.bigblogofgardening.com/guest-post-article-submission-guidelines/", "email": "N/A", "category": "Gardening", "notes": "Horticulture, agriculture, arboriculture experts."},
    {"name": "Homes Garden Idea", "url": "https://homesgardenidea.com/write-for-us-home-garden-design/", "email": "N/A", "category": "Gardening", "notes": "Home and garden design, landscaping."},
    {"name": "Prudential Cal", "url": "https://www.prudentialcal.com/write-for-us/", "email": "writer@prudentialcal.com", "category": "Real Estate", "notes": "Real estate, property, home improvement."},
    {"name": "SKN Real Estate", "url": "https://sknrealestate.com/write-for-us/", "email": "sknluxury@gmail.com", "category": "Real Estate", "notes": "Real estate, property, home decor, investing. 48h response."},
    {"name": "EstateMatee", "url": "https://estatematee.com/write-for-us-real-estate-guest-blogging-opportunity/", "email": "hassan@haashes.com", "category": "Real Estate", "notes": "Real estate guest blogging."},
    {"name": "I Love Aussie", "url": "https://iloveaussie.com/write-for-us-pest-control/", "email": "iloveaussiemarketing@gmail.com", "category": "Pest Control", "notes": "Min 1500 words. Send blog link + title + URL."},
    {"name": "Rescue Pest-Free", "url": "https://rescue-home.org/write-for-us/", "email": "rescueho@rescue-home.org", "category": "Pest Control", "notes": "1000+ words. Backlink from relevant article required."},
    {"name": "Fantastic Pest Control", "url": "https://www.fantasticpestcontrol.co.uk/blog/write-for-us/", "email": "N/A", "category": "Pest Control", "notes": "UK-based. Problem-solution format preferred."},
    {"name": "Window and Door Home Repairs", "url": "https://windowanddoorhomerepairs.com/become-a-guest-contributor/", "email": "N/A", "category": "Home Improvement", "notes": "Windows, doors, screens, shower enclosures, maintenance."},
    {"name": "Finderify", "url": "https://finderify.com/write-for-us/", "email": "hello@finderify.com", "category": "Home Services", "notes": "Subject: Guest Post Submission [Topic]. 5 business days. Location-based."},
    {"name": "Lovely Home Accents", "url": "https://www.lovelyhomeaccents.com/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Min 500 words. Home improvement, decor, interior, exterior."},
    {"name": "Flex House", "url": "https://www.flexhouse.org/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Home design, decorating, furniture, gardening, DIY, woodworking."},
    {"name": "Middle Height", "url": "https://middleheight.com/write-for-us/", "email": "N/A", "category": "Interior Design", "notes": "500-1500 words. Architecture, interior design, home decor, real estate."},
    {"name": "Classic Infrahomes Interior", "url": "https://classicinfrahomesinterior.com/write-for-us/", "email": "info@classicinfrahomesinterior.com", "category": "Interior Design", "notes": "Min 1000 words. Published in 24h."},
    {"name": "The Archspace", "url": "https://thearchspace.com/submit-your-article-guest-post/", "email": "N/A", "category": "Architecture", "notes": "Architecture, interiors, buildings, travel, construction, home decor."},
    {"name": "Lexangrit Design", "url": "https://design.lexangrit.com/write-for-us", "email": "sabina_khatun@lexangrit.com", "category": "Interior Design", "notes": "800-1800 words. Interior design, home improvement, furniture."},
    {"name": "Decor Girl", "url": "https://www.decorgirl.net/write-for-us-sponsored-posts/", "email": "N/A", "category": "Home Decor", "notes": "1000-3000 words."},
    {"name": "Archwhispers", "url": "https://archwhispers.com/guest-posting/", "email": "N/A", "category": "Architecture", "notes": "Paid/sponsored. Monthly guest posting plans."},
    {"name": "Harpley House", "url": "https://www.harpleyhouse.com/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "800-1500 words. Outdoor living, tree care, gardening, roofing, HVAC."},
    {"name": "3veta", "url": "https://3veta.com/write-for-us/", "email": "N/A", "category": "Home Office", "notes": "Work from home and remote work focus."},
    {"name": "Liverpool Living Space", "url": "https://liverpoollivingspace.co.uk/write-for-us/", "email": "admin@liverpoollivingspace.co.uk", "category": "Landscaping", "notes": "Gardening, landscaping, patios, outdoor furniture."},
    {"name": "Marketing2Business", "url": "https://www.marketing2business.com/patio-write-for-us/", "email": "contact@marketing2business.com", "category": "Outdoor Living", "notes": "Patio and outdoor living guest posts."},
    {"name": "Zuniga Roofing", "url": "https://zunigaroofinginc.com/write-for-us/", "email": "info@zunigaroofinginc.com", "category": "Roofing", "notes": "Free and sponsored. Roofing, HVAC, plumbing, flooring. 24-48h reply."},
    {"name": "Roofit Wise", "url": "https://roofitwise.com/write-for-us-roofing/", "email": "N/A", "category": "Roofing", "notes": "Expert roofing articles."},
    {"name": "Strange Buildings", "url": "https://strangebuildings.com/write-for-us-submit-guest-post/", "email": "editor@strangebuildings.com", "category": "Construction", "notes": "Roofing, HVAC, electrical, plumbing, real estate."},
    {"name": "Construction Buzz Point", "url": "https://constructionbuzzpoint.com/write-for-us/", "email": "N/A", "category": "Construction", "notes": "Carpentry, electrical, plumbing, HVAC."},
    {"name": "Carolina HVAC", "url": "https://wecarolinahvac.com/guest-post/", "email": "N/A", "category": "HVAC", "notes": "Plumbing, HVAC, heating, cooling."},
    {"name": "Top Blogin", "url": "https://www.topblogin.com/home-improvement-guest-post/", "email": "topblogin1@gmail.com", "category": "Home Improvement", "notes": "Min 1000 words. Home improvement, smart home, landscaping, real estate."},
    {"name": "Point 47 Design", "url": "https://www.point47.com/write-for-us/", "email": "john@point47.com", "category": "Home Decor", "notes": "Send article + proposed website. Published in hours."},
    {"name": "101 Home Security", "url": "https://www.101homesecurity.com/write-for-us/", "email": "N/A", "category": "Home Security", "notes": "Min 600 words. Home security unique content."},
    {"name": "Crazy Laura", "url": "https://www.crazylaura.com/write-for-us/", "email": "laura@crazylaura.com", "category": "DIY", "notes": "DIY tutorials and craft projects."},

    # === BATCH 3: High-authority blogs ===
    {"name": "Design Milk", "url": "https://design-milk.com/", "email": "N/A", "category": "Interior Design", "notes": "DR 81. Top-tier design publication."},
    {"name": "Hometalk", "url": "https://hometalk.com/", "email": "N/A", "category": "DIY", "notes": "DR 75. Major DIY and home decor community."},
    {"name": "Real Homes", "url": "https://realhomes.com/", "email": "N/A", "category": "Home Improvement", "notes": "DR 76. Major home and garden media publication."},
    {"name": "Active Rain", "url": "https://activerain.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 80. Major real estate community and blogging platform."},
    {"name": "Realty Times", "url": "https://realtytimes.com/", "email": "N/A", "category": "Real Estate", "notes": "DR 75. Established real estate news and advice publication."},
    {"name": "Build Review", "url": "https://build-review.com/", "email": "N/A", "category": "Construction", "notes": "DR 74. Construction and home improvement."},
    {"name": "Home Business Magazine", "url": "https://homebusinessmag.com/", "email": "N/A", "category": "Home Office", "notes": "DR 72. Home business, lifestyle, home office."},
    {"name": "Gardening Know How", "url": "https://www.gardeningknowhow.com", "email": "N/A", "category": "Gardening", "notes": "DA 74. One of the largest gardening resources online."},
    {"name": "The Home Trotters", "url": "https://thehometrotters.com/", "email": "N/A", "category": "Home Improvement", "notes": "DR 65. Global home improvement coverage."},
    {"name": "Decorator Advice", "url": "https://decoratoradvice.com/", "email": "N/A", "category": "Interior Design", "notes": "DR 63, DA 71. Decoration tips from experts."},
    {"name": "Fine Homes and Living", "url": "https://finehomesandliving.com/", "email": "N/A", "category": "Home Decor", "notes": "DR 63."},
    {"name": "Sampleboard", "url": "https://sampleboard.com/", "email": "info@sampleboard.com", "category": "Interior Design", "notes": "Mood boards, interior forecasting, color intelligence. Founded 2010."},
    {"name": "A House in the Hills", "url": "https://ahouseinthehills.com/", "email": "N/A", "category": "Home Decor", "notes": "DR 59, 23K monthly traffic."},
    {"name": "Home World Design", "url": "https://homeworlddesign.com/", "email": "N/A", "category": "Interior Design", "notes": "DR 60. Home design inspiration and tutorials."},
    {"name": "Homesteading.com", "url": "https://homesteading.com/", "email": "support@homesteading.com", "category": "DIY", "notes": "Food preservation, livestock, gardening, DIY, self-sufficient living."},
    {"name": "Old House to New Home", "url": "https://oldhousetonewhome.net/", "email": "N/A", "category": "Home Renovation", "notes": "DR 49. Home restoration focus."},
    {"name": "Architecture Art Designs", "url": "https://architectureartdesigns.com/", "email": "N/A", "category": "Architecture", "notes": "DR 67. Architecture and design inspiration."},
    {"name": "E-Architect", "url": "https://e-architect.com/", "email": "N/A", "category": "Architecture", "notes": "DA 70. Established architecture publication."},
    {"name": "The Pinnacle List", "url": "https://thepinnaclelist.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 61. Luxury real estate and lifestyle."},
    {"name": "Off the MRKT", "url": "https://offthemrkt.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 58. Real estate and home design. NYC market."},
    {"name": "Residence Style", "url": "https://residencestyle.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 64. Home decor and real estate."},
    {"name": "Storables", "url": "https://storables.com/write-for-us/", "email": "N/A", "category": "Home Organization", "notes": "DA 81. Home organization and storage solutions."},
    {"name": "House Affection", "url": "https://houseaffection.com/home-decor-write-for-us/", "email": "N/A", "category": "Home Decor", "notes": "DA 61. Submissions open."},
    {"name": "Ark Chase", "url": "https://arkchase.com/p/home-improvement-blog-write-for-us.html", "email": "N/A", "category": "Home Improvement", "notes": "DA 53."},
    {"name": "Home Design Ideas Pro", "url": "https://homedesignideaspro.com/write-for-us/", "email": "N/A", "category": "Interior Design", "notes": "DA 72. Premium home design ideas."},
    {"name": "Home Enhancement", "url": "https://homeenhance.home.blog/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "DA 91 (WordPress.com domain)."},
    {"name": "Home Improvement Cast", "url": "https://homeimprovementcast.co.uk/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "DA 51. UK. Celebrity homes, architecture, real estate, gardening."},
    {"name": "Opple House", "url": "https://opplehouse.com", "email": "N/A", "category": "Home Improvement", "notes": "DR 56, 34.6K traffic. 800-1500 words. Home decor, DIY, gardening."},
    {"name": "Gharpedia", "url": "https://gharpedia.com/", "email": "N/A", "category": "Construction", "notes": "DR 58. Construction and home improvement knowledge."},
    {"name": "House of Coco", "url": "https://houseofcoco.net/", "email": "N/A", "category": "Lifestyle", "notes": "DR 62. Lifestyle magazine: home, travel, design."},
    {"name": "Hudson Farmhouse", "url": "https://hudsonfarmhouse.com/", "email": "N/A", "category": "Home Decor", "notes": "DR 53. Farmhouse-style decor."},
    {"name": "Knock Off Decor", "url": "https://knockoffdecor.com/", "email": "N/A", "category": "DIY", "notes": "DR 48. Budget home decor DIY."},
    {"name": "Divine Lifestyle", "url": "https://divinelifestyle.com/", "email": "N/A", "category": "Lifestyle", "notes": "Lifestyle and home decor blog."},
    {"name": "Seasons in Colour", "url": "https://seasonsincolour.com/", "email": "N/A", "category": "Interior Design", "notes": "Color and decor inspiration."},
    {"name": "Top Inspired", "url": "https://topinspired.com/", "email": "N/A", "category": "Home Decor", "notes": "DA 70+. Inspiration and decor."},
    {"name": "The Owner Builder Network", "url": "https://theownerbuildernetwork.co/", "email": "N/A", "category": "Construction", "notes": "DA 60. DIY building and construction community."},
    {"name": "House Digest", "url": "https://housedigest.com", "email": "N/A", "category": "Home Improvement", "notes": "Major home improvement publication. High authority."},
    {"name": "Tiny House Plans", "url": "https://tinyhouseplans.com/", "email": "N/A", "category": "Tiny House", "notes": "DR 37. Tiny house plans and small home living."},

    # === BATCH 3B: More unique sites ===
    {"name": "London Home Style", "url": "https://londonhomestyle.co.uk/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "DIY, interior design, smart homes, sustainability."},
    {"name": "Web Tech Mantra", "url": "https://www.webtechmantra.com/home-improvement-write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Home automation, smart home, security, interior design."},
    {"name": "The Elegant Homes", "url": "https://theeleganthomes.com/home-improvement-write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement guest posts."},
    {"name": "Repaired Homes", "url": "https://repairedhomes.com/write-for-us-home-decor/", "email": "N/A", "category": "Home Decor", "notes": "Home decor, home improvement, real estate."},
    {"name": "Home Base Project", "url": "https://homebaseproject.org/home-decor-write-for-us-opportunity-at-homebaseproject/", "email": "N/A", "category": "Home Decor", "notes": "800-2000 words."},
    {"name": "KS Realty Agent", "url": "https://ksrealtyagent.com/home-improvement-write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement, decor, creative ideas."},
    {"name": "Khadiza Electricals", "url": "https://khadizaelectricals.com/write-for-us-home-decor/", "email": "info@khadizaelectricals.com", "category": "Home Decor", "notes": "Min 700 words (1000-1200 better). Home decor and gardening."},
    {"name": "House Decor List", "url": "https://housedecorelist.com/write-for-us-house-decor-list/", "email": "N/A", "category": "Home Decor", "notes": "800+ words. Practical home decor advice."},
    {"name": "Lovely Home Story", "url": "https://www.lovelyhomestory.com/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Home decor and improvement."},
    {"name": "The DIY Home Decor", "url": "https://thediyhomedecor.com/write-for-us/", "email": "N/A", "category": "DIY", "notes": "Homes and furniture guest post."},
    {"name": "Zingy Homes", "url": "https://zingyhomes.com/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement and decor."},
    {"name": "FreePress Directory", "url": "https://freepressdirectory.com/write-for-us-home-improvement-guest-posts-accepted/", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement guest posts directory."},
    {"name": "Housebeautifull", "url": "https://housebeautifull.org/write-for-us/", "email": "N/A", "category": "Home Decor", "notes": "Home decor and interior design guest posts."},
    {"name": "The Dedicated House", "url": "https://thededicatedhouse.com", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement and lifestyle."},
    {"name": "Grand Mama's House DIY", "url": "https://grandmashousediy.com", "email": "N/A", "category": "DIY", "notes": "DIY home projects and crafts."},
    {"name": "DIY Homey", "url": "https://diyhomey.com", "email": "N/A", "category": "DIY", "notes": "DIY home improvement."},
    {"name": "Heckhome", "url": "https://heckhome.com", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement and DIY."},
    {"name": "Home Briefings", "url": "https://homebriefings.com", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement news and tips."},
    {"name": "Find the Home Pros", "url": "https://findthehomepros.com", "email": "N/A", "category": "Home Services", "notes": "Home contractors and improvement professionals."},
    {"name": "Sourcednextdoor", "url": "https://sourcednextdoor.com", "email": "N/A", "category": "Home Services", "notes": "Local home services and improvement."},
    {"name": "Kreatecube", "url": "https://kreatecube.com", "email": "N/A", "category": "Interior Design", "notes": "Interior design and architecture resource."},
    {"name": "Re-Thinking The Future", "url": "https://re-thinkingthefuture.com", "email": "N/A", "category": "Architecture", "notes": "Architecture education and design."},
    {"name": "Illustrarch", "url": "https://illustrarch.com", "email": "N/A", "category": "Architecture", "notes": "Architecture illustrations and content."},
    {"name": "S3DA Design", "url": "https://s3da-design.com", "email": "N/A", "category": "Interior Design", "notes": "Interior design and 3D rendering."},
    {"name": "Architecture Beast", "url": "https://architecturebeast.com", "email": "N/A", "category": "Architecture", "notes": "Architecture content."},
    {"name": "Architecture Adrenaline", "url": "https://architectureadrenaline.com", "email": "N/A", "category": "Architecture", "notes": "Architecture and design inspiration."},
    {"name": "Architectures Style", "url": "https://architecturesstyle.com", "email": "N/A", "category": "Architecture", "notes": "Architectural styles and design."},
    {"name": "Fresh House Decor", "url": "https://freshhousedecor.com", "email": "N/A", "category": "Home Decor", "notes": "Home decor content."},
    {"name": "Your Home Design Center", "url": "https://yourhomedesigncenter.com", "email": "N/A", "category": "Home Decor", "notes": "Home design and decor."},
    {"name": "Style of Home", "url": "https://styleofhome.com", "email": "N/A", "category": "Home Decor", "notes": "Home styling content."},
    {"name": "Livinator", "url": "https://livinator.com/", "email": "N/A", "category": "Interior Design", "notes": "Home interior design and decor."},
    {"name": "Budget Savvy Diva", "url": "https://budgetsavvydiva.com/", "email": "N/A", "category": "DIY", "notes": "Budget home improvement and DIY."},
    {"name": "The Environmental Blog", "url": "https://theenvironmentalblog.org/", "email": "N/A", "category": "Sustainable Home", "notes": "Eco-friendly home improvements and energy efficiency."},
    {"name": "Project Cubicle", "url": "https://projectcubicle.com/", "email": "N/A", "category": "Home Office", "notes": "Home office design and productivity."},
    {"name": "EasyPalletIdeas", "url": "https://easypalletideas.com/", "email": "N/A", "category": "DIY", "notes": "DR 37. Pallet furniture and DIY decor."},
    {"name": "GudStory", "url": "https://gudstory.com/", "email": "N/A", "category": "Lifestyle", "notes": "Multi-topic: home improvement and lifestyle."},
    {"name": "Momooze", "url": "https://momooze.com/", "email": "N/A", "category": "Lifestyle", "notes": "Family lifestyle blog with home content."},
    {"name": "Time Business News", "url": "https://timebusinessnews.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 72. Broad business including real estate."},
    {"name": "Stuffablog", "url": "https://stuffablog.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 67. Multi-niche: home and real estate."},
    {"name": "City Gold Media", "url": "https://citygoldmedia.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 65. Real estate and business."},
    {"name": "Canada News Media", "url": "https://canadanewsmedia.ca/", "email": "N/A", "category": "Real Estate", "notes": "DA 64. Canadian news and real estate."},
    {"name": "Tech Crazee", "url": "https://techcrazee.com/", "email": "N/A", "category": "Smart Home", "notes": "DA 61. Technology covering smart home."},
    {"name": "Shifted Mag", "url": "https://shiftedmag.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 71. Real estate and home."},
    {"name": "News Anyway", "url": "https://newsanyway.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 68. News and real estate."},
    {"name": "ZShare", "url": "https://zshare.net/", "email": "N/A", "category": "Real Estate", "notes": "DA 72. Content sharing: home topics."},

    # === MORE UNIQUE SITES FROM ALL AGENTS ===
    {"name": "Green Living PDX", "url": "https://www.greenlivingpdx.com/category/guest-post/", "email": "N/A", "category": "Sustainable Home", "notes": "Green living. Portland-based."},
    {"name": "Home and Social", "url": "https://homeandsocial.com/write-for-us", "email": "N/A", "category": "Home Improvement", "notes": "Furnishing, security, DIY, upkeep, interior design."},
    {"name": "Artsy Home", "url": "https://artsyhome.com/", "email": "N/A", "category": "Home Decor", "notes": "DR 42. Home decor and design inspiration."},
    {"name": "Omni Home Ideas", "url": "https://omnihomeideas.com/", "email": "N/A", "category": "Interior Design", "notes": "DR 41. NCIDQ-certified designer."},
    {"name": "Living Pristine", "url": "https://livingpristine.com/", "email": "N/A", "category": "Home Decor", "notes": "DR 54. Luxury home aesthetics."},
    {"name": "Fly Architecture", "url": "https://flyarchitecture.net/", "email": "N/A", "category": "Architecture", "notes": "Global architecture insights."},
    {"name": "Luxury Interiors", "url": "https://luxuryinteriors.org/", "email": "N/A", "category": "Interior Design", "notes": "Upscale interior design."},
    {"name": "Middle Class Homes", "url": "https://middleclasshomes.net/", "email": "N/A", "category": "Home Improvement", "notes": "Budget-friendly home enhancements."},
    {"name": "Mobile Home Exteriors", "url": "https://mobilehomeexteriors.com/", "email": "N/A", "category": "Home Improvement", "notes": "Mobile home exterior improvements."},
    {"name": "Dr. Homey", "url": "https://drhomey.com/", "email": "N/A", "category": "Home Renovation", "notes": "Practical renovation and repair."},
    {"name": "Homes Crafto", "url": "https://homescrafto.com/", "email": "N/A", "category": "DIY", "notes": "Creative DIY and design."},
    {"name": "Harley Haze", "url": "https://harleyhaze.com/", "email": "N/A", "category": "Home Decor", "notes": "Home trends and lifestyle."},
    {"name": "Homoper", "url": "https://homoper.com/", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement and renovation."},
    {"name": "Worth View", "url": "https://worthview.com/", "email": "N/A", "category": "Lifestyle", "notes": "Lifestyle and home content."},
    {"name": "Incredible Things", "url": "https://incrediblethings.com/", "email": "N/A", "category": "Lifestyle", "notes": "Home gadgets and lifestyle."},
    {"name": "Elevated Magazines", "url": "https://elevatedmagazines.com/", "email": "N/A", "category": "Lifestyle", "notes": "Premium lifestyle: design content."},
    {"name": "Luxuria Lifestyle", "url": "https://luxurialifestyle.com/", "email": "N/A", "category": "Real Estate", "notes": "Luxury lifestyle and property."},
    {"name": "Suntrics", "url": "https://suntrics.com/", "email": "N/A", "category": "Smart Home", "notes": "Tech and home lifestyle."},
    {"name": "Art of Healthy Living", "url": "https://artofhealthyliving.com/", "email": "N/A", "category": "Lifestyle", "notes": "Healthy home and lifestyle."},
    {"name": "Captain Bobcat", "url": "https://captainbobcat.com/", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement and DIY."},
    {"name": "Cozmicway", "url": "https://cozmicway.com/", "email": "N/A", "category": "Lifestyle", "notes": "Lifestyle and home decor."},
    {"name": "Fresh Land Mag", "url": "https://freshlandmag.com/", "email": "N/A", "category": "Lifestyle", "notes": "Lifestyle and home decor magazine."},
    {"name": "Home Hearted", "url": "https://home-hearted.com/", "email": "N/A", "category": "Home Decor", "notes": "DA 58. Home decor and real estate."},
    {"name": "Answer Diary", "url": "https://answerdiary.com/", "email": "N/A", "category": "Real Estate", "notes": "DA 59. Multi-topic: real estate and home."},
    {"name": "Rooh Home", "url": "https://roohome.com/", "email": "N/A", "category": "Home Decor", "notes": "Multi-category home design."},
    {"name": "Fund Your Purpose", "url": "https://fundyourpurpose.org/", "email": "N/A", "category": "Real Estate", "notes": "Real estate investing and home financing."},
    {"name": "CEO Column", "url": "https://ceocolumn.com/", "email": "N/A", "category": "Real Estate", "notes": "Business covering real estate and home."},
    {"name": "Business to Mark", "url": "https://businesstomark.com/", "email": "N/A", "category": "Home Improvement", "notes": "Multi-niche including home improvement."},
    {"name": "Punsplanet", "url": "https://punsplanet.com/", "email": "N/A", "category": "Home Improvement", "notes": "DR 71. Multi-niche: home improvement."},
    {"name": "Recent Drone", "url": "https://recentdrone.com/", "email": "N/A", "category": "Smart Home", "notes": "DA 59. Tech: smart home and property."},
    {"name": "Sohomod", "url": "https://sohomod.com/", "email": "N/A", "category": "Furniture", "notes": "DR 35. Modern furniture and interior design."},
    {"name": "That Lifestyle", "url": "https://thatlyfestyle.com/", "email": "N/A", "category": "Lifestyle", "notes": "DR 30. Lifestyle with home content."},
    {"name": "Northernfeeling", "url": "https://northernfeeling.com/", "email": "N/A", "category": "Interior Design", "notes": "Scandinavian-influenced home decor."},
    {"name": "Design Mode 24", "url": "https://designmode24.com", "email": "N/A", "category": "Interior Design", "notes": "Modern style and remodeling."},
    {"name": "My Interior Palace", "url": "https://myinteriorpalace.com", "email": "N/A", "category": "Interior Design", "notes": "Elegant interiors."},
    {"name": "KD Architects", "url": "https://kdarchitects.net", "email": "N/A", "category": "Architecture", "notes": "Architecture and design execution."},
    {"name": "Active Property Care", "url": "https://activepropertycare.com", "email": "N/A", "category": "Home Services", "notes": "Property maintenance and care."},
    {"name": "Push Your Design", "url": "https://pushyourdesign.com", "email": "N/A", "category": "Home Decor", "notes": "Home decor and furniture."},
    {"name": "Ecovally Homes", "url": "https://ecovalleyhomes.com", "email": "N/A", "category": "Sustainable Home", "notes": "Eco-conscious building."},
    {"name": "Lifestyle Decor Hub", "url": "https://lifestyledecorhub.com", "email": "N/A", "category": "Home Decor", "notes": "Lifestyle and home decor."},
    {"name": "Homes Stars", "url": "https://homesstars.com", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement content."},
    {"name": "Architecture Ideas", "url": "https://architecturesideas.com", "email": "N/A", "category": "Architecture", "notes": "Architecture and design ideas."},
    {"name": "Sky Rye Design", "url": "https://skyryedesign.com", "email": "N/A", "category": "Interior Design", "notes": "Interior design blog."},
    {"name": "Upbeat Geek", "url": "https://www.upbeatgeek.com", "email": "info@upbeatgeek.com", "category": "Smart Home", "notes": "Home tech and improvement."},
    {"name": "VanEd", "url": "https://www.vaned.com", "email": "info@vaned.com", "category": "Real Estate", "notes": "Real estate education."},
    {"name": "Grass Desk", "url": "https://grassdesk.com", "email": "info@grassdesk.com", "category": "Real Estate", "notes": "Real estate content platform."},
    {"name": "Lawn Care Salem Oregon", "url": "https://lawncaresalem.com/gardening-guest-posts-write-for-us-on-our-gardening-blog/", "email": "N/A", "category": "Gardening", "notes": "Lawn care, organic gardening, vegetable garden, outdoor living."},
    {"name": "Montem Outdoor Gear", "url": "https://montemlife.com/blogs/hiking-blog/write-for-us-guest-posts", "email": "help@montemlife.com", "category": "Outdoor Living", "notes": "Submit title + synopsis + email + bio."},
    {"name": "Signature Outdoor Structures", "url": "https://signatureoutdoorstructures.com/write-for-us-sponsored-posts/", "email": "N/A", "category": "Outdoor Living", "notes": "Outdoor structures, pools, patios."},
    {"name": "The Outdoor Stores", "url": "https://theoutdoorstores.com/write-for-us-contribute-guest-post/", "email": "N/A", "category": "Outdoor Living", "notes": "Outdoors, survival, lifestyle, tech, home improvement."},
    {"name": "Master Woodsman", "url": "https://masterwoodsman.com/contact/submit-article/", "email": "N/A", "category": "Outdoor Living", "notes": "Woodcraft, outdoor living, bushcraft."},
    {"name": "Green Choice Lifestyle", "url": "https://greenchoicelifestyle.com/write-for-us-contribute-as-a-sustainability-guest-author/", "email": "N/A", "category": "Sustainable Home", "notes": "Sustainability guest authors."},
    {"name": "Tiny House Australia", "url": "https://tinyhouseaustralia.com/write-for-us/", "email": "N/A", "category": "Tiny House", "notes": "800-1500 words. Design, building, space-saving."},
    {"name": "Artiiseo", "url": "https://www.artiiseo.com/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Editorial fee $40 USD. 1200-2000 words."},
    {"name": "InnQuest", "url": "https://www.innquest.com/write-for-us/", "email": "N/A", "category": "Property Management", "notes": "Property management and hospitality software blog."},
    {"name": "CCIM Institute", "url": "https://www.ccim.com/real-estate-insights/commercial-connections-magazine/write-us", "email": "N/A", "category": "Real Estate", "notes": "Authoritative commercial real estate publication."},
    {"name": "Shoutn Australia", "url": "https://www.shoutnaustralia.com/write-for-us-home-security/", "email": "shoutnaustralia@gmail.com", "category": "Home Security", "notes": "Min 1500 words. Smart security systems."},
    {"name": "FeelSecure CCTV", "url": "https://www.feelsecurecctv.com/write-for-us/", "email": "N/A", "category": "Home Security", "notes": "Min 800 words. CCTV cameras, home security."},
    {"name": "Mattress Insider", "url": "https://www.mattressinsider.com/blog/write-for-us/", "email": "N/A", "category": "Home Living", "notes": "Mattress and furniture focus."},
    {"name": "Kitchen Renewal Tacoma", "url": "https://kitchenrenewaltacoma.com/write-for-us-home-improvement/", "email": "N/A", "category": "Kitchen & Bathroom", "notes": "Tacoma, WA. Kitchen, landscaping, plumbing, smart home."},
    {"name": "Home Furnishing News", "url": "https://homefurnishingnews.wordpress.com/write-for-us-submit-home-design-guest-post/", "email": "N/A", "category": "Furniture", "notes": "Home design and furniture submissions."},
    {"name": "Property Press Online", "url": "https://propertypressonline.co.uk", "email": "N/A", "category": "Real Estate", "notes": "UK property news and insights."},
    {"name": "Market Oracle", "url": "https://marketoracle.co.uk/", "email": "N/A", "category": "Real Estate", "notes": "DA 62. UK financial and real estate analysis."},
    {"name": "Ideal Magazine", "url": "https://idealmagazine.co.uk/", "email": "N/A", "category": "Lifestyle", "notes": "UK lifestyle and home decor."},
    {"name": "The Arches", "url": "https://thearches.co.uk/", "email": "N/A", "category": "Interior Design", "notes": "UK home decor and interior design."},
    {"name": "The Gingerbread House", "url": "https://the-gingerbread-house.co.uk/", "email": "N/A", "category": "Home Decor", "notes": "UK home decor and interior design."},
    {"name": "Illustrated Teacup", "url": "https://illustratedteacup.com/", "email": "N/A", "category": "Lifestyle", "notes": "Illustrated home decor and lifestyle."},
    {"name": "Standard of Lifestyle", "url": "https://standardoflifestyle.com/", "email": "N/A", "category": "Lifestyle", "notes": "Lifestyle: home improvement."},
    {"name": "Hollywood Mirrors", "url": "https://hollywoodmirrors.co.uk/", "email": "N/A", "category": "Home Decor", "notes": "DR 49. UK home decor retailer with blog."},
    {"name": "Home Decor Ideas USA", "url": "https://homedecorideasusa.com/", "email": "N/A", "category": "Home Decor", "notes": "US audience home decor."},
    {"name": "MyFancyHouse", "url": "https://myfancyhouse.com", "email": "N/A", "category": "Home Improvement", "notes": "DA 79. Home design and improvement."},
    {"name": "Cascade BuildTech", "url": "https://www.cascadebuildtech.com", "email": "info@cascadebuildtech.com", "category": "Construction", "notes": "Construction and building technology."},
    {"name": "Write For Us Architecture", "url": "https://writeforusarchitecture.com/write-for-us-home-improvement/", "email": "N/A", "category": "Architecture", "notes": "Architecture and home improvement."},
    {"name": "Home Improvement Warehouse", "url": "https://homeimprovementware.com/write-for-us-submit-guest-post/", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement niche."},
    {"name": "Radical FM", "url": "https://radical.fm/write-for-us-home-improvement/", "email": "N/A", "category": "Home Improvement", "notes": "Technology and business: home improvement section."},
    {"name": "Autistic Baker", "url": "https://autisticbaker.com/home-improvement-guest-post-write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Home improvement write-for-us."},
    {"name": "Arcgo PH", "url": "https://www.arcgo-ph.com/write-for-us-construction-hardware-realestate-amp-home-improvement-guest-posts/", "email": "N/A", "category": "Construction", "notes": "Construction, hardware, real estate."},
    {"name": "Get News 360", "url": "https://getnews360.com", "email": "info@getnews360.com", "category": "Lifestyle", "notes": "General news including home topics."},
    {"name": "GBOBER", "url": "https://gbober.com", "email": "contact@gbober.com", "category": "Real Estate", "notes": "Real estate blog."},
    {"name": "Vahuk", "url": "https://vahuk.com", "email": "contact@vahuk.com", "category": "Real Estate", "notes": "Property and real estate."},
    {"name": "Housing Market News UK", "url": "https://housingmarketnews.co.uk", "email": "N/A", "category": "Real Estate", "notes": "UK housing market and renovation news."},
    {"name": "Jaya Pest", "url": "https://www.jayapest.com/write-for-us/", "email": "N/A", "category": "Pest Control", "notes": "Pest control topics."},
    {"name": "Auto Insura", "url": "https://www.autoinsura.org/write-for-us/", "email": "N/A", "category": "Home Insurance", "notes": "Min 1000 words. Insurance and finance."},
    {"name": "My Top Insurance Blogs", "url": "https://mytopinsuranceblogs.com/write-for-us/", "email": "N/A", "category": "Home Insurance", "notes": "Homeowners, renters, property coverage."},
    {"name": "Roofing Cost Calculator UK", "url": "https://roofingcostcalculator.co.uk/write-for-us/", "email": "N/A", "category": "Roofing", "notes": "UK roofing expertise."},
    {"name": "London Home Expert", "url": "https://londonhomeexpert.co.uk/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "DA 42. London-focused."},
    {"name": "Kyuhyung Cho", "url": "https://www.kyuhyungcho.com/write-for-us-interior-design-home-improvement/", "email": "N/A", "category": "Interior Design", "notes": "Home improvement and interior design."},
    {"name": "Home Decor Write For Us", "url": "https://homedecorwriteforus.wordpress.com", "email": "N/A", "category": "Home Decor", "notes": "General home decor guest post aggregator."},
    {"name": "Lowcountry Style and Living", "url": "https://lowcountrystyleandliving.com/write-for-us-guest-posts-stories-accepted/", "email": "N/A", "category": "Outdoor Living", "notes": "$99 processing fee. Outdoor living focus."},
    {"name": "Bathnketchin", "url": "https://bathnketchin.justoborn.com/write-for-us/", "email": "N/A", "category": "Kitchen & Bathroom", "notes": "Bathrooms, kitchens, remodeling, interior design."},
    {"name": "My Garden and Patio", "url": "https://mygardenandpatio.com", "email": "N/A", "category": "Gardening", "notes": "Garden and patio ideas."},
    {"name": "Home and Garden Listings UK", "url": "https://homeandgardenlistings.co.uk", "email": "N/A", "category": "Gardening", "notes": "UK home and garden directory."},
    {"name": "Dusk Digital", "url": "https://www.duskdigital.io/write-for-us/", "email": "N/A", "category": "Home Improvement", "notes": "Digital marketing agency with home improvement blog."},
    {"name": "SecureBlitz", "url": "https://secureblitz.com/write-for-us/", "email": "N/A", "category": "Home Security", "notes": "Security, VPN, antivirus, home security."},
    {"name": "GuestPost123", "url": "https://guestpost123.com/home-security/", "email": "N/A", "category": "Home Security", "notes": "Aggregator platform for home security sites."},
    {"name": "Terelee Homes", "url": "https://tereleehomes.com/security/", "email": "N/A", "category": "Home Security", "notes": "Safety, fire prevention, smart locks. Woodland Hills, CA."},
    {"name": "PropertyHome India", "url": "https://propertyhome.in", "email": "info@propertyhome.in", "category": "Real Estate", "notes": "India-focused real estate."},
    {"name": "Home Plans India", "url": "https://homeplansindia.com", "email": "N/A", "category": "Architecture", "notes": "Floor plans. India-focused."},
    {"name": "Saoarchitects", "url": "https://saoarchitects.com", "email": "N/A", "category": "Architecture", "notes": "Architecture firm blog."},
]

# Deduplicate by domain
seen_domains = set()
unique_sites = []

for site in all_sites:
    try:
        domain = urlparse(site["url"]).netloc.lower().replace("www.", "")
    except:
        domain = site["url"]

    if domain not in seen_domains:
        seen_domains.add(domain)
        unique_sites.append(site)

# Sort by category
unique_sites.sort(key=lambda x: (x["category"], x["name"]))

# Save
output_path = "/Users/vladimirprihodko/Папка тест/fixcraftvp/seo-articles/target_sites_massive.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(unique_sites, f, ensure_ascii=False, indent=2)

# Stats
total = len(unique_sites)
with_email = [s for s in unique_sites if s["email"] not in ("N/A", "", None)]
categories = {}
for s in unique_sites:
    cat = s["category"]
    categories[cat] = categories.get(cat, 0) + 1

print(f"\n=== SUMMARY ===")
print(f"Total unique sites: {total}")
print(f"Sites with email: {len(with_email)}")
print(f"\n--- By Category ---")
for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
    print(f"  {cat}: {count}")

print(f"\n--- Top Sites with Emails (for priority outreach) ---")
for i, s in enumerate(with_email[:20], 1):
    print(f"  {i}. {s['name']} — {s['email']} ({s['category']})")

print(f"\nSaved to: {output_path}")
